<a href="https://colab.research.google.com/github/valleryuh/CSST-101/blob/main/De_Guzman%2C_Jan_Valerie_L__CSST101_Lab4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create Database

In [1]:
students <- data.frame(
  Student_ID = c("S001","S002","S003","S004","S005", "S006", "S007", "S008"),
  Programming_Grade = c(88, 72, 91, 78, 65, 85, 74, 82),
  Math_Grade = c(85, 70, 88, 80, 68, 90, 73, 79),
  Attendance = c(92, 80, 95, 88, 70, 91, 76, 85),
  Prerequisite = c("Yes", "No")
)

students

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
1 S001       88                85         92         Yes
2 S002       72                70         80         No
3 S003       91                88         95         Yes
4 S004       78                80         88         No
5 S005       65                68         70         Yes
6 S006       85                90         91         No
7 S007       74                73         76         Yes
8 S008       82                79         85         No

2. Explore the Data

In [2]:
nrow(students)
ncol(students)

max(students$Programming_Grade)
max(students$Attendance)
max(students$Math_Grade)

mean(students$Attendance)
mean(students$Programming_Grade)
mean(students$Math_Grade)

mean(students$Attendance)
mean(students$Programming_Grade)
min(students$Math_Grade)

[1] 8

[1] 5

[1] 91

[1] 95

[1] 90

[1] 84.625

[1] 79.375

[1] 79.125

[1] 84.625

[1] 79.375

[1] 68

3.Enter a Student ID
```

In [3]:
Student_ID <- readline("Enter Student ID: ")
print(Student_ID)

Enter Student ID: S001
[1] "S001"

4. Search the Data Frame

In [4]:
students <- students[
  students$Student_ID == Student_ID,
]
students

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
1 S001       88                85         92         Yes

5. Check if the Students Exists

In [6]:
student <- students[
  students$Student_ID == Student_ID,
]
if (nrow(student) == 0) {
  print("Student ID not found.")
} else {
  print(student)
}

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
1       S001                88         85         92          Yes

6. Exract Student Information

In [17]:
programming <- students$Programming_Grade
Math_Grade <- students$Math_Grade
Attendance <- students$Attendance
Prerequisite <- students$Prerequisite

cat("Programming Grade: ", programming)
cat("Math Grade: ", Math_Grade, "%")
cat("Attendance: ", Attendance)
cat("Prerequisite: ", Prerequisite)

Programming Grade:  88Math Grade:  85 %Attendance:  92Prerequisite:  Yes

7. Implement the Rules

In [20]:
if (programming >= 80 &&
    Math_Grade >= 75 &&
    Attendance >= 80 &&
    Prerequisite == "Yes") {

  classification <- "Eligible"

} else if (programming >= 75 &&
           Math_Grade >= 70 &&
           Attendance >= 75) {

  classification <- "Conditionally Eligible"

} else {

  classification <- "Not Eligible"
}

c("Classification:", classification)

[1] "Classification:" "Eligible"

8. Apply The Function To All Students

In [19]:
check_eligibility <- function(programming, Math_Grade, Attendance, Prerequisite) {

  if (programming >= 80 &&
      Math_Grade >= 75 &&
      Attendance >= 80 &&
      Prerequisite == "Yes") {

    return("Eligible")

  } else if (programming >= 75 &&
             Math_Grade >= 70 &&
             Attendance >= 75) {

    return("Conditionally Eligible")

  } else {

    return("Not Eligible")
  }
}

students$Classification <- mapply(
  check_eligibility,
  students$Programming_Grade,
  students$Math_Grade,
  students$Attendance,
  students$Prerequisite
)

students

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
1 S001       88                85         92         Yes
  Classification
1 Eligible

9. Create Recommendation Rules

In [22]:
recommendation <- function(programming, math, attendance, prereq) {

  if (programming >= 80 &&
      Math_Grade >= 75 &&
      Attendance >= 80 &&
      Prerequisite == "Yes") {

    return("Highly Recommended")

  } else if (programming >= 75 &&
             Math_Grade >= 70 &&
             Attendance >= 75) {

    return("Recommended with Improvement")

  } else {

    return("Needs Improvement")
  }
}

students$Recommendation <- mapply(
  recommendation,
  students$Programming_Grade,
  students$Math_Grade,
  students$Attendance,
  students$Prerequisite
)

students

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
1 S001       88                85         92         Yes
  Classification Recommendation
1 Eligible       Highly Recommended

10. Final Output

In [23]:
# Ask For Student ID
student_id <- readline("Enter Student ID: ")

# Find Student
student <- students[students$Student_ID == student_id, ]

if (nrow(student) == 0) {

  cat("\nStudent not found.\n")

} else {

  # Extract Student Information
  programming <- student$Programming_Grade
  math <- student$Math_Grade
  attendance <- student$Attendance
  prereq <- student$Prerequisite

  # Implement Rules
  if (programming >= 80 &&
      math >= 75 &&
      attendance >= 80 &&
      prereq == "Yes") {

    classification <- "Eligible"

  } else if (programming >= 75 &&
             math >= 70 &&
             attendance >= 75) {

    classification <- "Conditionally Eligible"

  } else {

    classification <- "Not Eligible"
  }

  # Recommendation Rules
  if (classification == "Eligible") {

    recommendation <- "Proceed with enrollment"

  } else if (classification == "Conditionally Eligible") {

    recommendation <- "Consult academic adviser"

  } else {

    recommendation <- "Not recommended for enrollment"
  }

  # Final Output
  cat("\n==========================================\n")
  cat("          COURSE ENROLLMENT ADVISER\n")
  cat("==========================================\n\n")

  cat("Student ID:", student$Student_ID, "\n\n")

  cat("Programming Grade:", programming, "\n")
  cat("Math Grade:", math, "\n")
  cat("Attendance:", attendance, "%\n")
  cat("Prerequisite:", prereq, "\n\n")

  cat("Enrollment Status:\n")
  cat(classification, "\n\n")

  cat("Recommendation:\n")
  cat(recommendation, "\n\n")

  cat("==========================================\n")
}

Enter Student ID: S001

==========================================
          COURSE ENROLLMENT ADVISER
==========================================

Student ID: S001

Programming Grade: 88
Math Grade: 85
Attendance: 92 %
Prerequisite: Yes

Enrollment Status:
Eligible

Recommendation:
Proceed with enrollment

==========================================